// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-PxGum5ok8hslO6W3ukrfk2QQXQZY7Jw',
    appId: '1:204364042575:web:609af09c1abd89b4d0f53a',
    messagingSenderId: '204364042575',
    projectId: 'ma-basic-app',
    authDomain: 'ma-basic-app.firebaseapp.com',
    storageBucket: 'ma-basic-app.firebasestorage.app',
    measurementId: 'G-8EVK1Q1R4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd7PtO1xCr6jGPuo764TuBrAQrBPY6Uck',
    appId: '1:204364042575:android:824029ddb27e92e8d0f53a',
    messagingSenderId: '204364042575',
    projectId: 'ma-basic-app',
    storageBucket: 'ma-basic-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Qiu1_NBpne9glbkPOPlcrkTOixeO7gA',
    appId: '1:204364042575:ios:73ae47765e1b3b82d0f53a',
    messagingSenderId: '204364042575',
    projectId: 'ma-basic-app',
    storageBucket: 'ma-basic-app.firebasestorage.app',
    iosBundleId: 'com.example.maBaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Qiu1_NBpne9glbkPOPlcrkTOixeO7gA',
    appId: '1:204364042575:ios:73ae47765e1b3b82d0f53a',
    messagingSenderId: '204364042575',
    projectId: 'ma-basic-app',
    storageBucket: 'ma-basic-app.firebasestorage.app',
    iosBundleId: 'com.example.maBaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-PxGum5ok8hslO6W3ukrfk2QQXQZY7Jw',
    appId: '1:204364042575:web:5ef69da534b5ef6cd0f53a',
    messagingSenderId: '204364042575',
    projectId: 'ma-basic-app',
    authDomain: 'ma-basic-app.firebaseapp.com',
    storageBucket: 'ma-basic-app.firebasestorage.app',
    measurementId: 'G-L50F7Z1TZK',
  );
}
